baseURL = 'https://innersource.soprasteria.com/nirpendra.kumar/mypersonal-doc.git'
languageCode = 'en-us'
title = 'My Doc'
theme = 'hugo-theme-relearn'
relativeURLs = true
canonifyURLs = true
ignoreLogs = ['warning-goldmark-raw-html']
[params]
  # Relearn theme-specific parameters
  colorTheme = "light"
  layout = "wide"



